// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fazpviopnsxzvtdfytwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhenB2aW9wbnN4enZ0ZGZ5dHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MDE5NDMsImV4cCI6MjA1Nzk3Nzk0M30.x2P4ymri6WiSx7DAk_M7UDHKVBfQ1wrqM3YILJtKec8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);